/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocalizedRouteImport } from './routes/_localized'
import { Route as LocalizedIndexRouteImport } from './routes/_localized/index'
import { Route as LocalizedApiDomainChar123ServerDomainChar125RouteImport } from './routes/_localized/$apiDomain/{-$serverDomain}'

const LocalizedRoute = LocalizedRouteImport.update({
  id: '/_localized',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizedIndexRoute = LocalizedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalizedRoute,
} as any)
const LocalizedApiDomainChar123ServerDomainChar125Route =
  LocalizedApiDomainChar123ServerDomainChar125RouteImport.update({
    id: '/$apiDomain/{-$serverDomain}',
    path: '/$apiDomain/{-$serverDomain}',
    getParentRoute: () => LocalizedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LocalizedIndexRoute
  '/$apiDomain/{-$serverDomain}': typeof LocalizedApiDomainChar123ServerDomainChar125Route
}
export interface FileRoutesByTo {
  '/': typeof LocalizedIndexRoute
  '/$apiDomain/{-$serverDomain}': typeof LocalizedApiDomainChar123ServerDomainChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_localized': typeof LocalizedRouteWithChildren
  '/_localized/': typeof LocalizedIndexRoute
  '/_localized/$apiDomain/{-$serverDomain}': typeof LocalizedApiDomainChar123ServerDomainChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$apiDomain/{-$serverDomain}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$apiDomain/{-$serverDomain}'
  id:
    | '__root__'
    | '/_localized'
    | '/_localized/'
    | '/_localized/$apiDomain/{-$serverDomain}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocalizedRoute: typeof LocalizedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_localized': {
      id: '/_localized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LocalizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_localized/': {
      id: '/_localized/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LocalizedIndexRouteImport
      parentRoute: typeof LocalizedRoute
    }
    '/_localized/$apiDomain/{-$serverDomain}': {
      id: '/_localized/$apiDomain/{-$serverDomain}'
      path: '/$apiDomain/{-$serverDomain}'
      fullPath: '/$apiDomain/{-$serverDomain}'
      preLoaderRoute: typeof LocalizedApiDomainChar123ServerDomainChar125RouteImport
      parentRoute: typeof LocalizedRoute
    }
  }
}

interface LocalizedRouteChildren {
  LocalizedIndexRoute: typeof LocalizedIndexRoute
  LocalizedApiDomainChar123ServerDomainChar125Route: typeof LocalizedApiDomainChar123ServerDomainChar125Route
}

const LocalizedRouteChildren: LocalizedRouteChildren = {
  LocalizedIndexRoute: LocalizedIndexRoute,
  LocalizedApiDomainChar123ServerDomainChar125Route:
    LocalizedApiDomainChar123ServerDomainChar125Route,
}

const LocalizedRouteWithChildren = LocalizedRoute._addFileChildren(
  LocalizedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LocalizedRoute: LocalizedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
