/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SApiDomainChar123ServerDomainChar125RouteImport } from './routes/s/$apiDomain/{-$serverDomain}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SApiDomainChar123ServerDomainChar125Route =
  SApiDomainChar123ServerDomainChar125RouteImport.update({
    id: '/s/$apiDomain/{-$serverDomain}',
    path: '/s/$apiDomain/{-$serverDomain}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$apiDomain/{-$serverDomain}': typeof SApiDomainChar123ServerDomainChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$apiDomain/{-$serverDomain}': typeof SApiDomainChar123ServerDomainChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$apiDomain/{-$serverDomain}': typeof SApiDomainChar123ServerDomainChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$apiDomain/{-$serverDomain}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$apiDomain/{-$serverDomain}'
  id: '__root__' | '/' | '/s/$apiDomain/{-$serverDomain}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SApiDomainChar123ServerDomainChar125Route: typeof SApiDomainChar123ServerDomainChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$apiDomain/{-$serverDomain}': {
      id: '/s/$apiDomain/{-$serverDomain}'
      path: '/s/$apiDomain/{-$serverDomain}'
      fullPath: '/s/$apiDomain/{-$serverDomain}'
      preLoaderRoute: typeof SApiDomainChar123ServerDomainChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SApiDomainChar123ServerDomainChar125Route:
    SApiDomainChar123ServerDomainChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
